# Tomcat
server:
  port: 8083

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Apereo-Learning-Analytics-Initiative/lai-config
          searchPaths: defaults
          
security:
  user:
    name: apereo
    password: openanalytics

